### ISSUE TITLE
Some subjects/objects in the edges file are not present in the nodes file

### ISSUE THREAD

**Issue by kaiwenho** [UCDenver-ccp/kgx-export#2]
I noticed that some subjects/objects in the edges file are not present in the nodes file. For instance, the curie CHEBI:37845 appears in the edges file (e.g., CHEBI:37845 biolink:treats MONDO:0002794...), but it is not listed in the nodes file. This presents a challenge because the lack of category information means that the CHEBI:37845 biolink:treats MONDO:0002794 edge could be missed when a user specifies a category of the subject in the query. Thank you!

**Comment by edgargaticaCU** [comment]
@kaiwenho The code issue has been addressed in PR #3
